//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BP_WebSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Match
    {
        public int matchId { get; set; }
        public Nullable<int> roundId { get; set; }
        public Nullable<int> takimID1 { get; set; }
        public Nullable<int> takimID2 { get; set; }
        public Nullable<int> skor1 { get; set; }
        public Nullable<int> skor2 { get; set; }
        public string grupAdi { get; set; }
    
        public virtual Round Round { get; set; }
    }
}
