//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BP_WebSite.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BP_DatabaseEntities : DbContext
    {
        public BP_DatabaseEntities()
            : base("name=BP_DatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Kullanici> Kullanici { get; set; }
        public virtual DbSet<Match> Match { get; set; }
        public virtual DbSet<Round> Round { get; set; }
        public virtual DbSet<Takim> Takim { get; set; }
        public virtual DbSet<Turnuva> Turnuva { get; set; }
    }
}
