//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BP_WebSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Takim
    {
        public int takimId { get; set; }
        public Nullable<int> turnuvaId { get; set; }
        public string takimAdi { get; set; }
        public int pts { get; set; }
        public int avg { get; set; }
        public string grupAdi { get; set; }
    
        public virtual Turnuva Turnuva { get; set; }
    }
}
