//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BP_WebSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Turnuva
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Turnuva()
        {
            this.Round = new HashSet<Round>();
            this.Takim = new HashSet<Takim>();
        }
    
        public int turnuvaId { get; set; }
        public Nullable<int> kullaniciId { get; set; }
        public string turnuvaAdi { get; set; }
        public string turnuvaCesidi { get; set; }
    
        public virtual Kullanici Kullanici { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Round> Round { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Takim> Takim { get; set; }
    }
}
